# Generated by Django 4.0.5 on 2022-07-10 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flavors',
            new_name='Flavor',
        ),
    ]
