# Generated by Django 4.0.5 on 2022-07-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_location_flavor_created_at_flavor_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='modified_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='modified_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='screen',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='screen',
            name='modified_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='screenview',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='screenview',
            name='modified_at',
            field=models.DateTimeField(),
        ),
    ]
