# Generated by Django 4.0.5 on 2022-07-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_flavor_created_at_alter_flavor_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
